public enum MatrixType {
    AT_LEAST_ONE_BONUS,
    NO_BONUS,
    ALL_SAME_SYMBOLS,
    ALL_DIFFERENT_SYMBOLS,
    AT_LEAST_THREE_SIMILAR,
    MORE_THAN_THREE_SIMILAR,
    MORE_THAN_THREE_SIMILAR_WITH_BONUS
}
